# Generated by Django 5.2.7 on 2025-11-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='architecte',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Architecte'),
        ),
        migrations.AddField(
            model_name='projet',
            name='control_technique',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Contrôle Technique'),
        ),
        migrations.AddField(
            model_name='projet',
            name='delai_execution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Délai d’Exécution'),
        ),
        migrations.AddField(
            model_name='projet',
            name='etude_geotechnique',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Étude Géotechnique'),
        ),
        migrations.AddField(
            model_name='projet',
            name='etude_technique',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Étude Technique'),
        ),
        migrations.AddField(
            model_name='projet',
            name='intitule',
            field=models.CharField(default='Sans titre', max_length=255, verbose_name='Intitulé du Projet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projet',
            name='situation',
            field=models.CharField(choices=[('en_cours', 'En Cours'), ('acheve', 'Achevé'), ('en_arret', 'En Arrêt')], default='en_cours', max_length=20, verbose_name='Situation'),
        ),
        migrations.AddField(
            model_name='projet',
            name='topographe',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Topographe'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_debut',
            field=models.DateField(verbose_name='Date de Début'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_fin_prevue',
            field=models.DateField(verbose_name='Date de Fin Prévue'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='province',
            field=models.CharField(default='Sans titre', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='taux_avancement',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
