# Generated by Django 5.2.7 on 2025-11-03 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_projet_architecte_projet_control_technique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topo_date_debut', models.DateField(blank=True, null=True)),
                ('topo_date_fin', models.DateField(blank=True, null=True)),
                ('topo_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('geo_date_debut', models.DateField(blank=True, null=True)),
                ('geo_date_fin', models.DateField(blank=True, null=True)),
                ('geo_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('archi_date_debut', models.DateField(blank=True, null=True)),
                ('archi_date_fin', models.DateField(blank=True, null=True)),
                ('archi_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('etud_date_debut', models.DateField(blank=True, null=True)),
                ('etud_date_fin', models.DateField(blank=True, null=True)),
                ('etud_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ctrl_date_debut', models.DateField(blank=True, null=True)),
                ('ctrl_date_fin', models.DateField(blank=True, null=True)),
                ('ctrl_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('trav_date_debut', models.DateField(blank=True, null=True)),
                ('trav_date_fin', models.DateField(blank=True, null=True)),
                ('trav_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_arret', models.DateField(blank=True, null=True)),
                ('taux_avancement', models.PositiveIntegerField(default=0)),
                ('taux_paiement', models.PositiveIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='projets.projet')),
            ],
        ),
    ]
